//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestNewProjectForNetCore
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// C1.
    /// </summary>
    // *** Start programmer edit section *** (C1 CustomAttributes)

    // *** End programmer edit section *** (C1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("C1E", new string[] {
            "name as \'Name\'"})]
    [View("C1L", new string[] {
            "name as \'Name\'"})]
    public class C1 : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        // *** Start programmer edit section *** (C1 CustomMembers)

        // *** End programmer edit section *** (C1 CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (C1.name CustomAttributes)

        // *** End programmer edit section *** (C1.name CustomAttributes)
        [StrLen(255)]
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (C1.name Get start)

                // *** End programmer edit section *** (C1.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (C1.name Get end)

                // *** End programmer edit section *** (C1.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (C1.name Set start)

                // *** End programmer edit section *** (C1.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (C1.name Set end)

                // *** End programmer edit section *** (C1.name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "C1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View C1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("C1E", typeof(IIS.TestNewProjectForNetCore.C1));
                }
            }
            
            /// <summary>
            /// "C1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View C1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("C1L", typeof(IIS.TestNewProjectForNetCore.C1));
                }
            }
        }
    }
}
